dependencies {
    implementation project(':common')

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    // @AuthenticationPrincipal 타입만 필요하다. user 모듈과 같은 이유로 스타터가 아니라 core 만.
    implementation 'org.springframework.security:spring-security-core'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
